// Note: Make sure to sort by specificity, matching is done from top to bottom
//       and will stop at the first match.
// Example:
// - van der
// - van de
// - van

const DutchPrepositons = [
    "aan den ",
    "aan der ",
    "aan de ",
    "aan het ",
    "aan 't ",
    "bij den ",
    "bij de ",
    "bij het ",
    "bij 't ",
    "boven d'",
    "de die le ",
    "de die ",
    "de l'",
    "de las ",
    "de la ",
    "de le ",
    "de van der ",
    "in den ",
    "in der ",
    "in het ",
    "in de ",
    "in 't ",
    "onder den ",
    "onder de ",
    "onder het ",
    "onder 't ",
    "over den ",
    "over de ",
    "over het ",
    "over 't ",
    "op den ",
    "op der ",
    "op de ",
    "op gen ",
    "op het ",
    "op 't ",
    "op ten ",
    "van de l'",
    "van den ",
    "van der ",
    "van de ",
    "van gen ",
    "van het ",
    "van la ",
    "van 't ",
    "van ter ",
    "uit den ",
    "uit de ",
    "uit het ",
    "uit 't ",
    "uit ten ",
    "uit te ",
    "uijt den ",
    "uijt de ",
    "uijt het ",
    "uijt 't ",
    "uijt ten ",
    "uijt te ",
    "voor den ",
    "voor de ",
    "voor in 't ",

    "aan ",
    "af ",
    "bij ",
    "den ",
    "der ",
    "de ",
    "d'",
    "het ",
    "in ",
    "onder ",
    "op ",
    "over ",
    "'s ",
    "'t ",
    "ten ",
    "ter ",
    "te ",
    "tot ",
    "uit ",
    "uijt ",
    "van ",
    "ver ",
    "voor "
];

export default DutchPrepositons;
